version: "3"
services:
  pg-tasks:
    container_name: pg-tasks
    image: postgres:9.6
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=password
  jenkins:
    container_name: jenkins-tasks
    privileged: true
    user: root
    image: jenkins/jenkins:2.204.4
    ports:
      - 8083:8080
      - 50000:50000